name: Prettier Formatting
on:
  pull_request:
    branches:
      - "**"
jobs:
  prettier:
    name: Prettier
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: Install prettier
        run: npm install prettier prettier-plugin-organize-imports prettier-plugin-tailwindcss
      - name: Format with Prettier
        run: npm run prettier:format
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Formatted with Prettier (GitHub Action)
          branch: ${{ github.head_ref }}
      - name: Check formatting with Prettier
        run: npm run prettier:check:ci
